package com.example.rentakucapstone.dataKendaraan

enum class ModelMotor(val value: String) {
    ACHIEVER("achiever"),
    APACHE("apache"),
    AX1("ax1"),
    BALIUS("balius"),
    BANDIT("bandit"),
    BENLY("benly"),
    BLAZE("blaze"),
    BOXER("boxer"),
    CB125("cb 125"),
    CB4("cb4"),
    CBHORNET("cb hornet"),
    CBSHINE("cb shine"),
    CBTRIGGER("cb trigger"),
    CBUNICORN("cb unicorn"),
    CBBLADE("cb blade"),
    CBR("cbr"),
    CBZ("cbz"),
    CD("cd"),
    CDDOWN("cd down"),
    CD110("cd 110"),
    CD125("cd 125"),
    CD70("cd 70"),
    CD90("cd 90"),
    CMCUSTOM("cm custom"),
    CENTRA("centra"),
    CENTURO("centuro"),
    CIVIC("civic"),
    DTRACKER("d tracker"),
    D7("d7"),
    DR("dr"),
    DT("dt"),
    DTM("dtm"),
    DZM("dzm"),
    DZR("dzr"),
    DASH("dash"),
    DAWN("dawn"),
    DJEBEL("djebel"),
    DREAM("dream"),
    DUKE("duke"),
    DUKE200("duke 200"),
    ESTRELLA("estrella"),
    FTR("ftr"),
    FZ("fz"),
    FZS("fz s"),
    FZ25("fz25"),
    FAZER("fazer"),
    FLAME("flame"),
    GN125("gn 125"),
    GN250("gn 250"),
    GS125("gs 125"),
    GIXXER("gixxer"),
    GLADIATOR("gladiator"),
    GLAMOUR("glamour"),
    GRASSTRACKER("grass tracker"),
    GUSTO("gusto"),
    HFDAWN("hf dawn"),
    HFDELUXE("hf deluxe"),
    HORNET("hornet"),
    HUNK("hunk"),
    IGNITOR("ignitor"),
    INTRUDER("intruder"),
    JADE("jade"),
    KARIZMA("karizma"),
    LD("ld"),
    LX("lx"),
    LIBERO("libero"),
    LITTLECUB("little cub"),
    MD("md"),
    MT15("mt 15"),
    MAGNA("magna"),
    MATE("mate"),
    METRO("metro"),
    MONSTER("monster"),
    NV400("nv400"),
    NAVI("navi"),
    NINJA("ninja"),
    NTORQ("ntorq"),
    PCX("pcx"),
    PASSION("passion"),
    PASSIONPLUS("passion plus"),
    PASSIONPRO("passion pro"),
    R15("r15"),
    RC("rc"),
    REBEL("rebel"),
    RIO("rio"),
    SX("sx"),
    SZRR("sz-rr"),
    SAFARI("safari"),
    SALUTO("saluto"),
    SAVAGESUPRA("savage supra"),
    SCOOTYZEST("scooty zest"),
    SKYBORN("sky born"),
    SKYLINE("skyline"),
    SPLENDER("splender"),
    SPLENDERPLUS("splender plus"),
    SPLENDERISMART("splender i smart"),
    STARCITYPLUS("star city plus"),
    STARSPORT("star sport"),
    STREAK("streak"),
    STRYKER("stryker"),
    STUNNER("stunner"),
    SUPERCLUB("super club"),
    SUPERSPLENDER("super splender"),
    TTR("ttr"),
    TW("tw"),
    TZR("tzr"),
    TROPICA("tropica"),
    TUONO("tuono"),
    TWISTER("twister"),
    UZO125("uzo 125"),
    VTR("vtr"),
    VICTOR("victor"),
    VIRAGO("virago"),
    WARRIOR("warrior"),
    WEGO("wego"),
    XBLADE("x-blade"),
    XL100("xl 100"),
    XLSUPER("xl super"),
    XLR("xlr"),
    XR("xr"),
    XTREAM("xtream"),
    ZOOMER("zoomer")

}